
/****** Object:  Database [Distribution]    Script Date: 11/18/2013 8:59:10 AM ******/
CREATE DATABASE [Distribution]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Distribution', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Distribution.mdf' , SIZE = 10240KB , MAXSIZE = 102400KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'Distribution_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\Distribution_log.ldf' , SIZE = 5120KB , MAXSIZE = 51200KB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Distribution] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Distribution].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Distribution] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Distribution] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Distribution] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Distribution] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Distribution] SET ARITHABORT OFF 
GO

ALTER DATABASE [Distribution] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Distribution] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Distribution] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Distribution] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Distribution] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Distribution] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Distribution] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Distribution] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Distribution] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Distribution] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Distribution] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Distribution] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Distribution] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Distribution] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Distribution] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Distribution] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Distribution] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Distribution] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Distribution] SET RECOVERY FULL 
GO

ALTER DATABASE [Distribution] SET  MULTI_USER 
GO

ALTER DATABASE [Distribution] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Distribution] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Distribution] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Distribution] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Distribution] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Distribution] SET  READ_WRITE 
GO


